### ISSUE TITLE
session_id when specified outside properties throws error

### ISSUE THREAD

**Issue by twainm** [rudderlabs/rudder-transformer#283]
I have encountered an issue with Amplitude and hence wanted to reach out here as I might have to share some specifics
: I am using Rudder's batch API call to push events to Amplitude. The session_id https://developers.amplitude.com/docs/batch-event-upload-api is something I need outside properties so that Amplitude doesn't set it to -1.

This is what I try to send
`{
    "batch": [
        {
            "type": "identify",
            "userId": "ubcdfghi0001",
            "session_id": 1598597129,
            "context": {
                "traits": {
                    "device_id": "adddd0001",
                    "device_os": "ios",
                    "device_make": "apple iphone",
                    "app_version": "v1.0",
                    "timestamp": "2020-08-28 09:00:00"
                },
                "library": {
                    "name": "http"
                }
            }
        },
{
            "type": "track",
            "event": "clicked app",
            "userId": "ubcdfghi0001",
            "session_id": 1598597129,
            "context": {
                "library": {
                    "name": "http"
                }
            },
            "properties": {
                "event_id": "u001e01",
                "attempt_id": "u001a01",
                "timestamp": "2020-08-28 09:01:00"
            }
        }
    ]
}`
If I put session_id inside properties or inside traits then the message is sent successfully but session_id is always -1 in Amplitude.
But if I put them outside to overrite the value then I get the following exception on Rudder Transformer
`TypeError: payload.session_id.lastIndexOf is not a function
    at getSessionId (/home/node/app/v0/destinations/am/transform.js:73:28)
    at responseBuilderSimple (/home/node/app/v0/destinations/am/transform.js:155:24)
    at processSingleMessage (/home/node/app/v0/destinations/am/transform.js:261:10)
    at toSendEvents.forEach.sendEvent (/home/node/app/v0/destinations/am/transform.js:326:19)
    at Array.forEach (<anonymous>)
    at Object.process (/home/node/app/v0/destinations/am/transform.js:325:16)
    at Promise.all.events.map (/home/node/app/versionedRouter.js:65:44)
    at Array.map (<anonymous>)
    at handleDest (/home/node/app/versionedRouter.js:61:12)
    at router.post (/home/node/app/versionedRouter.js:120:15) []
TypeError: payload.session_id.lastIndexOf is not a function
    at getSessionId (/home/node/app/v0/destinations/am/transform.js:73:28)
    at responseBuilderSimple (/home/node/app/v0/destinations/am/transform.js:155:24)
    at processSingleMessage (/home/node/app/v0/destinations/am/transform.js:261:10)
    at toSendEvents.forEach.sendEvent (/home/node/app/v0/destinations/am/transform.js:326:19)
    at Array.forEach (<anonymous>)
    at Object.process (/home/node/app/v0/destinations/am/transform.js:325:16)
    at Promise.all.events.map (/home/node/app/versionedRouter.js:65:44)
    at Array.map (<anonymous>)
    at handleDest (/home/node/app/versionedRouter.js:61:12)
    at router.post (/home/node/app/versionedRouter.js:120:15) []
TypeError: payload.session_id.lastIndexOf is not a function
    at getSessionId (/home/node/app/v0/destinations/am/transform.js:73:28)
    at responseBuilderSimple (/home/node/app/v0/destinations/am/transform.js:155:24)
    at processSingleMessage (/home/node/app/v0/destinations/am/transform.js:261:10)
Attachment file type: document`

Code:  master

**Comment by arnab-p** [comment]
https://github.com/rudderlabs/rudder-transformer/pull/292
