### ISSUE TITLE
`Cannot read property 'type' of undefined` with user transforms

### ISSUE THREAD

**Issue by pierreavizou** [rudderlabs/rudder-transformer#293]
I have updated to the latest version of the Transformer Docker image, and this error starts showing up if I use user transforms for the Customerio destination. 

As a consequence, events are not forwarded to the destination. 

Even the simplest transform function (`function transform(events) { return events; }`) causes the error to occur. 

It goes away if I disable user transforms for that destination. 

Rolling back to a previous version fixes the issue. 

Below a the complete stack trace as it shows up in the transformer's logs. 

```
TypeError: Cannot read property 'type' of undefined
2020-09-08T11:27:23.721744650Z     at processSingleMessage (/home/node/app/v0/destinations/customerio/transform.js:194:31)
2020-09-08T11:27:23.721749954Z     at Object.process (/home/node/app/v0/destinations/customerio/transform.js:224:18)
2020-09-08T11:27:23.721753255Z     at Promise.all.events.map (/home/node/app/versionedRouter.js:65:44)
2020-09-08T11:27:23.721756337Z     at Array.map (<anonymous>)
2020-09-08T11:27:23.721760181Z     at handleDest (/home/node/app/versionedRouter.js:61:12)
2020-09-08T11:27:23.721763115Z     at router.post (/home/node/app/versionedRouter.js:120:15)
2020-09-08T11:27:23.721778815Z     at dispatch (/home/node/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
2020-09-08T11:27:23.721783777Z     at next (/home/node/app/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
2020-09-08T11:27:23.721786540Z     at /home/node/app/node_modules/koa-router/lib/router.js:346:16
2020-09-08T11:27:23.721805807Z     at dispatch (/home/node/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32) []```

**Comment by akashrpo** [comment]
The event seems to be flowing properly for the user transformer.
